# Generated by Django 5.0.6 on 2024-07-03 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_post_colour_scheme_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='colour_scheme',
            field=models.CharField(default='yellow', max_length=20, verbose_name='Colour Scheme'),
        ),
    ]
