# Generated by Django 5.0.6 on 2024-07-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_post_colour_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='colour_scheme',
            field=models.CharField(default='ysunset', max_length=20, verbose_name='Colour Scheme'),
        ),
    ]
