# Generated by Django 5.0.6 on 2024-07-19 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_settings_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='post',
        ),
        migrations.AlterField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='front_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/<django.db.models.fields.CharField>/'),
        ),
    ]
