# Generated by Django 5.0.6 on 2024-07-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_galleryimage_image_galleryimage_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryimage',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
