# Generated by Django 5.0.6 on 2024-07-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_post_front_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/settings/'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='value',
            field=models.CharField(max_length=500, null=True, verbose_name='Value'),
        ),
    ]
