# Generated by Django 5.0.6 on 2024-07-21 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_settings_image_alter_settings_value'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/settings/')),
            ],
        ),
        migrations.RemoveField(
            model_name='settings',
            name='image',
        ),
    ]
