# Generated by Django 5.0.6 on 2024-07-21 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_avatar_remove_settings_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avatar',
            old_name='image',
            new_name='avatar',
        ),
    ]
