# Generated by Django 5.0.6 on 2024-07-23 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_image_avatar_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
